### ISSUE TITLE
linux to linux remote connection

### ISSUE THREAD

**Issue by niveshd** [joelspadin/vscode-remote-x11#21]
Is the extension intended to work from linux to linux remote connection?

Previously, I was using windows to remotely access linux. With xming active in windows, everything worked like a charm. Can we do the same, if we use linux to linux connections? I assume you would want me to run some xserver in linux. If so, what should I use. A connection using terminal is not automatically detected by the extension.

Thanks!

**Comment by ChaosinaCan** [comment]
It should work, though I've never tried it because I only have one PC running Linux at the moment. I'll have to see if I can get the vscode remote server running on a Raspberry Pi or something so I can test it.

**Comment by niveshd** [comment]
Hi, thanks for the reply. Should I be running some program in the background (e.g. Xming in windows)?

There is one more thing, the remote server and my home pc share the same home folder. I am not sure if this is relevant though.

**Comment by topatopa** [comment]
It doesn't seem to work. The connection seems to work and the DISPLAY variable is set but nothing gets displayed on the screen.  It is like the application opens but the extension doesn't have access to the actual local display.

I see "x11 accept: 127.0.0.1" in the Remote X11 (SSH) output whenever I launch an application but like I said nothing is displayed.

Tested it using
Host PC: Kubuntu 18.04 (kde)
Remote PC: centos 7 (gnome3)

I tested all these cases after setting DISPLAY when applicable:
- X11Forwarding from external terminal and launching application from remote vscode terminal (**WORKS**)
- X11Forwarding from another vscode  window's integrated terminal and launching application from remote vscode terminal (**WORKS**)
- X11Forwarding from the extension and launching application from integrated terminal in SSH session (**DOESNT WORK**)
- X11Forwarding from the extension and launching application from external terminal (**DOESNT WORK**)

**Comment by ChaosinaCan** [comment]
The most I've been able to figure out so far is that the local machine's X server appears to be rejecting the connection, but I don't know why yet.

**Comment by DavidLanders95** [comment]
I have the same issue trying to get this to work from a linux machine to a linux machine. It appears to connect, but then the matpplotlib figure does not show up when I compile my programme. I've tried to use the extension settings to set the correct display value to 13.0, but I don't think it made a difference.

**Comment by darkvertex** [comment]
I'm also doing Linux to Linux and when I try to call a command with an X GUI it disconnects the entire session and says "_Extension host terminated unexpectedly._" but there's nothing in the logs that I could see. :/

**Comment by justin-gerhardt** [comment]
I've tried to debug this a bit more. 
The issue with the connection being refused is caused by modern linux distro's disabling tcp connections for X.
Whatever starts X in the boot process adds -nolisten tcp to the X arguments.
There will be a distro/login manager specifc option somewhere to disable this. 
Doing so, however introduces security issues (on my system this opens X up to connections from anywhere). 

After setting the appropriate flag launching applications on the remote system now displays the error "Invalid MIT-MAGIC-COOKIE-1 keyxhost:  unable to open display "localhost:10.0"".
I don't know how ssh forwarding sessions local connect/authenticate to x (unix socket?). You should probably look at replicating that behaviour.

**Comment by joelspadin** [comment]
Based on https://github.com/mscdex/ssh2, it looks like ssh2 uses a random number for the cookie by default. I'm not sure where to get the value the X server is expecting.

https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely suggests running
```sh
xhost +local: 
```
as a workaround to grant any local user access to the screen. Note that you shouldn't run that on a multi-user system as it would grant other users access as well.

**Comment by neonish** [comment]
There's definitely an issue with the plugin connecting to the right display for ubuntu to ubuntu connections. I finally managed to get it to work with [wrobelda's answer](https://github.com/microsoft/vscode-remote-release/issues/267#issuecomment-491665490) (you won't need this plugin for this).

Consider this just a workaround though, as my remote server keeps changing the display variable every few reconnects so you need to change it manually every time.

**Comment by justin-gerhardt** [comment]
I've done a bit more digging on implementing this properly, Connecting to the unix socket is implemented in https://github.com/joelspadin/vscode-remote-x11/pull/35 
The behavior for generating auth tokens using the openssh client seems to depend on if it's making a trusted or untrusted X11 connection (-Y vs -X).

### untrusted
it creates a tmp folder and executes `xauth -f /tmp/<tmp folder name>/xauthfile generate :<display name> MIT-MAGIC-COOKIE-1 untrusted timeout 1260`  which creates a file with a token that's registered to the xserver.
It then runs `xauth -f /tmp/<tmp folder name>/xauthfile :<display name> list` and parses the result for the token.

### trusted
It runs `xauth :<display name> list` and parses the result for the token in the existing default Xauthority file. 


### Connecting
 Once this token is known it appears it can be passed https://github.com/joelspadin/vscode-remote-x11/blob/51e105acc05d0b1918e631ba565880392e8d75ab/ssh/src/extension.ts#L87-L90
using the parameter cookie as "a hex string or a Buffer containing the raw cookie value (which will be converted to a hex string)" per the ssh2 documentation on the exec and shell functions.

I'll probably create a pull request to implement this in a week or so

**Comment by joelspadin** [comment]
Thanks for the PR! I did find the documentation for passing the cookie, but I wasn't familiar enough with X11 authentication and couldn't find any good documentation on how to figure out what the cookie should be. I'll gladly accept help for getting that working.
