### ISSUE TITLE
I can connect to my ubuntu server, but the remote-X11(ssh) extensiton log out "Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR".

### ISSUE THREAD

**Issue by yjianzhu** [joelspadin/vscode-remote-x11#57]
I have two public keys in the authorized_keys file of my ubuntu server.
When I use my laptop, all things are right, which uses the first public key.

But the second public key, form another windows PC, 
the remote-X11(ssh) extensiton log out "Error: Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR".

Thanks for your extension. Hope for your reply.

**Comment by erosminer** [comment]
I came across the same thing
